CREATE TABLE public.profiles (
  user_id uuid PRIMARY KEY,
  display_name text NOT NULL DEFAULT '' CHECK (char_length(display_name) <= 100),
  avatar_url text CHECK (avatar_url IS NULL OR char_length(avatar_url) <= 1000),
  preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  caregiver_name text CHECK (caregiver_name IS NULL OR char_length(caregiver_name) <= 100),
  caregiver_email text CHECK (caregiver_email IS NULL OR char_length(caregiver_email) <= 255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own profile" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users create own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own profile" ON public.profiles FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE TABLE public.medicines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
  dose text NOT NULL CHECK (char_length(dose) BETWEEN 1 AND 100),
  dose_time time NOT NULL,
  period text NOT NULL CHECK (period IN ('Morning', 'Afternoon', 'Night')),
  stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'taken', 'skipped', 'snoozed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.medicines TO authenticated;
GRANT ALL ON public.medicines TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.medicines_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.medicines_id_seq TO service_role;
ALTER TABLE public.medicines ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own medicines" ON public.medicines FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users create own medicines" ON public.medicines FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own medicines" ON public.medicines FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own medicines" ON public.medicines FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE TABLE public.dose_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  medicine_id bigint NOT NULL REFERENCES public.medicines(id) ON DELETE CASCADE,
  status text NOT NULL CHECK (status IN ('taken', 'skipped', 'snoozed')),
  scheduled_for timestamptz NOT NULL DEFAULT now(),
  recorded_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.dose_history TO authenticated;
GRANT ALL ON public.dose_history TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.dose_history_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.dose_history_id_seq TO service_role;
ALTER TABLE public.dose_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own dose history" ON public.dose_history FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users create own dose history" ON public.dose_history FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own dose history" ON public.dose_history FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users delete own dose history" ON public.dose_history FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE INDEX medicines_user_id_idx ON public.medicines(user_id);
CREATE INDEX dose_history_user_id_idx ON public.dose_history(user_id);
CREATE INDEX dose_history_medicine_id_idx ON public.dose_history(medicine_id);